# fly.toml app configuration file generated for pihole06 on 2023-11-27T00:01:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "adsfree"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  DNSMASQ_LISTENING = "all"
  INTERFACE = "eth0"
  PH_VOLUME = "/mnt/ph_data"

[[mounts]]
  source = "ph_data"
  destination = "/mnt/ph_data"

[[services]]
  protocol = "tcp"
  internal_port = 80
  auto_stop_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 8443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 53
  auto_stop_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 853
    handlers = ["tls"]
  [services.concurrency]
    type = "connections"
    hard_limit = 150
    soft_limit = 100

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  auto_stop_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 150
    soft_limit = 100

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
